name: deploy

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker compose
      run: docker compose -p analytics-dashboard up --build -d
